# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: "5"
  - nodejs_version: "4"
  - nodejs_version: "0.12"
  - nodejs_version: "0.10"
  - nodejs_version: "1"
  - nodejs_version: "2.5"
  - nodejs_version: "3.2"

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - IF %nodejs_version% LSS 1 (npm install -g npm@2)
  - IF %nodejs_version% LSS 1 set PATH=%APPDATA%\npm;%PATH%
  # Typical npm stuff.
  - npm cache clean
  - npm install --msvs_version=%MSVS_VERSION%

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"

matrix:
  fast_finish: true

cache:
  - node_modules -> package.json                                        # local npm modules
